### PR TITLE
MYFACES-4460: remove JSTL(Tags) dependency

### PR DESCRIPTION
**Pull request by pnicolucci**
https://issues.apache.org/jira/browse/MYFACES-4460

Also removing the import for `javax.servlet.jsp`, `javax.servlet.jsp.tagext`, and `javax.servlet.jsp.jstl.core`

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Good catch.

**Comment by pnicolucci** [comment]
@melloware @tandraschko I see we still have some tld files as well in the code base. Any argument against me removing those as part of this PR as well? If not I'll work on that tomorrow and ask for another set of reviews.

**Comment by pnicolucci** [comment]
I think we can remove the following from the `impl/pom.xml`:

   

>                 <execution>
>                         <id>makecoretld</id>
>                         <configuration>
>                             <xmlFile>META-INF/myfaces_core.tld</xmlFile>
>                             <templateFile>myfaces_core12.vm</templateFile>
>                             <modelIds>
>                                 <modelId>myfaces-api</modelId>
>                                 <modelId>myfaces-impl</modelId>
>                             </modelIds>
>                             <params>
>                                 <shortname>f</shortname>
>                                 <uri>http://java.sun.com/jsf/core</uri>
>                                 <displayname>JSF core tag library.</displayname>
>                                 <description>This tag library implements the standard JSF core tags.</description>
>                             </params>
>                         </configuration>
>                         <goals>
>                             <goal>make-config</goal>
>                         </goals>
>                     </execution>
> 
>                     <execution>
>                         <id>makehtmltld</id>
>                         <configuration>
>                             <xmlFile>META-INF/myfaces_html.tld</xmlFile>
>                             <xmlBaseFile>src/main/conf/META-INF/myfaces_html-base.tld</xmlBaseFile>
>                             <templateFile>myfaces_html12.vm</templateFile>
>                             <params>
>                                 <shortname>h</shortname>
>                                 <uri>http://java.sun.com/jsf/html</uri>
>                                 <displayname>JSF HTML tag library.</displayname>
>                                 <description>This tag library implements the standard JSF HTML tags.</description>
>                             </params>
>                             <modelIds>
>                                 <modelId>myfaces-api</modelId>
>                             </modelIds>
>                         </configuration>
>                         <goals>
>                             <goal>make-config</goal>
>                         </goals>
>                     </execution>

**Comment by pnicolucci** [comment]
pushed the changes mentioned above into this PR. Let me know if you have any questions or concerns. My builds locally look good with all the tests passing.

**Comment by melloware** [comment]
I defer to @tandraschko on the TLD question :)

**Comment by pnicolucci** [comment]
As a note it does look like these were removed in Mojarra during the "JSP removal": https://github.com/eclipse-ee4j/mojarra/commit/96757f39d47bf05060103b67933eb6afe9fd9278

**Pull request merged**
