### PR TITLE
MYFACES-4548 4.0: org.apache.myfaces.USE_LAMBDA_METAFACTORY default false

### PR DESCRIPTION
**Pull request by melloware**
I don't know where the documentation is.  Is it another project on GitHub?
https://issues.apache.org/jira/browse/MYFACES-4548

### CODE REVIEW

**Comment by volosied** [comment]
Only documentation I know of: https://myfaces.apache.org/#/core40

https://github.com/apache/myfaces-homepage/blob/main/core40.md

**Comment by melloware** [comment]
Thank you I updated that MD to have the default be `false`

**Review by pnicolucci — APPROVED** [review]
This looks good, thanks! I linked it to https://issues.apache.org/jira/browse/MYFACES-4548 can you update 2.3-next as well for consistency? Or do you want me to do that?

**Comment by melloware** [comment]
I can submit for 2.3-next.

**Pull request merged**
