### PR TITLE
MYFACES-4606

### PR DESCRIPTION
**Pull request by werpu**
Fix for MyFaces 4606, checkboxes and radio buttons are not appended automatically if unchecked!

### CODE REVIEW

**Comment by werpu** [comment]
I will leave this pull request open for a few days and merge on monday!

**Comment by volosied** [comment]
Running tests. Will report later. Thanks for getting this PR up!

**Comment by werpu** [comment]
does it fix the issue for you?

**Comment by volosied** [comment]
Haven't run the the full tck yet, but the one test that failed is now passing. I should have all the results by tomorrow. I think the changes should be fine. 

Can you get a PR for the older JS code base and I can port it all the other affected branches? Thanks!

**Comment by tandraschko** [comment]
Tests failing?

**Comment by werpu** [comment]
No PR for the older codebase needed, it is not affected!

**Pull request merged**
