### PR TITLE
MYFACES-4533: JS only for a better solution

### PR DESCRIPTION
**Pull request by werpu**
By suggestion of @tandraschko he wants to work on a better solution for the issue!

Providing a pull request against main for the js only changes, so that he can take over with a hopefully better solution to the issue!

### CODE REVIEW

**Comment by volosied** [comment]
With Thomas' commit https://github.com/apache/myfaces/commit/9ad6f971ca601be609ca72dfbc90637d81ed9f22, does that means this is ready to be merged?

**Comment by tandraschko** [comment]
werner will run the TCK with my changes + this PR - and if this works, we are done, yup

**Comment by werpu** [comment]
Hi I will run the TCK now with the changes

**Comment by werpu** [comment]
Sorry not working: here is the full log.

I basically merged from master into this pull request and ran the namespace TCK against it:
https://gist.github.com/werpu/b952f800565b9bcc113a071aea2dc4ad
Here is the full log, it fails on component buildup level!

**Comment by werpu** [comment]
added the latest main to this pull request...

**Comment by tandraschko** [comment]
thanks werner
i thought it should work but i restored your "resolvePrefixFromRequest" now and commited

it would be great if you can try again

**Comment by werpu** [comment]
Looks good now
image

I will run the rest of the tck tests to see if there is any difference to before, if not then I will push one last time and we will be ready to merge!

**Comment by werpu** [comment]
Faces 2.3 OK!
image

Faces 2.2 OK!
image
My personal integration tests pass as well

image

I will merge the latest main code in then we can merge back!
I will do the code merge for my typescript pull request on monday then!

**Comment by werpu** [comment]
I think we are ready to merge now, if it is ok, even the machine checks have passed!
Thanks Thomas for helping out here!

**Comment by tandraschko** [comment]
Sure
Please merge and close the jira issue
Thanks!

**Comment by werpu** [comment]
done, I will do all the necessary merges for the typescript branch on monday. After that lets talk there on how we are going to proceed!

**Pull request merged**
