### PR TITLE
Normalize files based on .gitattributes

### PR DESCRIPTION
**Pull request by melloware**
This normalizes all files in master using `git add --renormalize .`

### CODE REVIEW

**Comment by volosied** [comment]
Sorry for creating a conflict. If you could rebase, I'll approve. 

I encountered this myself with my recent PR.

**Comment by melloware** [comment]
Just run `git add --renormalize .` on your codebase.  That basically runs through all files making they match gitattributes.

**Comment by melloware** [comment]
@volosied can you run `git add --renormalize .` on your local setup and see what it says needs to be fixed?  To compare it to mine?

**Comment by volosied** [comment]
I'm seeing 48 files as well.  They all appear to match those in your PR.

**Comment by volosied** [comment]
Rebase & Merge?

**Pull request merged**
