### PR TITLE
MYFACES-4082 Fix 'binding' when referencing composite components

### PR DESCRIPTION
**Pull request by luigiJsonar**
Code that 'sets' the value of the binding attribute for composite components. Inspired on:
org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate#createComponent

### CODE REVIEW

**Comment by tandraschko** [comment]
@luigiJsonar 

the ComponentTagHandlerDelegate contains the following, before setting the value:
if (PhaseId.RESTORE_VIEW.equals(faces.getCurrentPhaseId()))

Could you please if it makes sense to add this if?

**Comment by tandraschko** [comment]
@luigiJsonar 

Could you please try this:

https://gist.github.com/tandraschko/2f8e15bcbf8affc63df26b25f9259584

If it works fine, i will apply it

**Comment by luigiJsonar** [comment]
Applied the suggested changes and it works fine.

**Comment by luigiJsonar** [comment]
I'd be more than happy to apply any other suggestions, open more PRs for previous versions, test it... I don't understand why it had to be your commit, not mine. Can you point me to any documentation on how to contribute to this repo? I need that because I might be missing something but IMHO I tried to contribute and you just got my code and didn't even mention me on it.

**Comment by tandraschko** [comment]
Sorry, please don't take it personally. I didn't see that you applied my changes, so i commited my version, which was inspired by your version and the original code. 

You can just contribute by opening issues, trigger discussions on the dev mailinst list and provide patches/Pull Requests.

**Pull request closed without merging**
