### PR TITLE
MYFACES-4696: 5.0 Undertow connection abort handling

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko here is what I came up with please review

### CODE REVIEW

**Comment by melloware** [comment]
I have never gotten an error before I wasn't sure how to reproduce it?  If you give me a hint i can try it.

**Comment by tandraschko** [comment]
i have a quarkus project primefaces poseidon
sometimes after restart, and reload page i get this
its propably only occurs in firefox as it loads both from cache and from network -> if cache is faster and available, network connection is aborted

**Comment by melloware** [comment]
Weird I am trying in in Firefox and I see those NS_BINDING_ABORTED but nothing in my logs.

image

**Comment by tandraschko** [comment]
cant replicate it currently (think it will soon there again) but its safe to merge at least for 5.0

**Pull request merged**
