### PR TITLE
MYFACES-4273 close() JarFile in Classpath

### PR DESCRIPTION
**Pull request by wtlucy**
see https://issues.apache.org/jira/browse/MYFACES-4273

### CODE REVIEW

**Comment by tandraschko** [comment]
basically +1
however a try/resource statement would be a bit nicer probably :)

**Comment by wtlucy** [comment]
@tandraschko how's this?  I'll still need to use the try finally method for the 2.0 and 2.1 branches

**Comment by tandraschko** [comment]
looks good if it still works the same :)

**Comment by wtlucy** [comment]
Yeah, it's the same logic.  I'll put this fix in 2.2, 2.3, and 3.0.

**Pull request merged**
