### PR TITLE
MYFACES-4662 + Spec 1760

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4662
https://issues.apache.org/jira/browse/MYFACES-4664

### CODE REVIEW

**Comment by volosied** [comment]
@melloware  I'm hitting this in the quarkus tests? Not sure why -- it doesn't look related to my changes....? Can you test / investigate this PR?

```
-------------------------------------------------------------------------------
Test set: org.apache.myfaces.core.extensions.quarkus.showcase.QuarkusMyFacesShowcaseTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.128 s <<< FAILURE! - in org.apache.myfaces.core.extensions.quarkus.showcase.QuarkusMyFacesShowcaseTest
org.apache.myfaces.core.extensions.quarkus.showcase.QuarkusMyFacesShowcaseTest  Time elapsed: 2.128 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type PushContext and qualifiers [@Default]
	- java member: org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView#helloChannel
	- declared on CLASS bean [types=[java.io.Serializable, org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView, java.lang.Object], qualifiers=[@Default, @Any, @Named("socketView")], target=org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type PushContext and qualifiers [@Default]
	- java member: org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView#helloChannel
	- declared on CLASS bean [types=[java.io.Serializable, org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView, java.lang.Object], qualifiers=[@Default, @Any, @Named("socketView")], target=org.apache.myfaces.core.extensions.quarkus.showcase.view.SocketView]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:477)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
	... 13 more
```

**Comment by melloware** [comment]
yep let me look.

**Comment by melloware** [comment]
OK I did a git pull of the 4.1 branch and everything is passing for me with `mvn clean install`.  

logs below

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.myfaces.core.extensions.quarkus.showcase.QuarkusMyFacesShowcaseTest
Using org.apache.myfaces.webapp.MyFacesContainerInitializer
MyFaces Core Bean Validation support disabled
MyFaces Core CDI support enabled
Running on PrimeFaces 12.0.0
UT026005: Adding programmatic server endpoint class org.apache.myfaces.push.EndpointImpl for path /jakarta.faces.push/{channel}
Scanning for context init parameters not defined. It is not necessary to define them all into your web.xml, they are just provided here for informative purposes. To disable this messages set org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS config param to 'false'
Init context parameter found 'jakarta.faces.PROJECT_STAGE' set to 'Development'
No context init parameter 'jakarta.faces.RESOURCE_EXCLUDES' found, using default value '.class .jsp .jspx .properties .xhtml .groovy'.
No context init parameter 'jakarta.faces.STATE_SAVING_METHOD' found, using default value 'server'.
No context init parameter 'jakarta.faces.FULL_STATE_SAVING_VIEW_IDS' found.
No context init parameter 'jakarta.faces.PARTIAL_STATE_SAVING' found, using default value 'true (false with 1.2 webapps)'.
No context init parameter 'jakarta.faces.SERIALIZE_SERVER_STATE' found, using default value 'false'.
No context init parameter 'jakarta.faces.DEFAULT_SUFFIX' found, using default value '.xhtml'.
No context init parameter 'jakarta.faces.FACELETS_SUFFIX' found, using default value '.xhtml'.
No context init parameter 'jakarta.faces.FACELETS_VIEW_MAPPINGS' found.
No context init parameter 'jakarta.faces.FACELETS_BUFFER_SIZE' found, using default value '1024'.
No context init parameter 'jakarta.faces.FACELETS_DECORATORS' found.
No context init parameter 'jakarta.faces.FACELETS_LIBRARIES' found.
No context init parameter 'jakarta.faces.FACELETS_REFRESH_PERIOD' found, using default value '0, -1 in Production'.
No context init parameter 'jakarta.faces.FACELETS_SKIP_COMMENTS' found.
No context init parameter 'jakarta.faces.VALIDATE_EMPTY_FIELDS' found, using default value 'auto'.
Init context parameter found 'jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL' set to 'true'
No context init parameter 'org.apache.myfaces.CLEAR_INPUT_WHEN_SUBMITTED_VALUE_IS_NULL_OR_EMPTY' found, using default value 'true'.
No context init parameter 'jakarta.faces.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE' found, using default value 'false'.
No context init parameter 'jakarta.faces.VIEWROOT_PHASE_LISTENER_QUEUES_EXCEPTIONS' found, using default value 'false'.
No context init parameter 'jakarta.faces.DATETIMECONVERTER_DEFAULT_TIMEZONE_IS_SYSTEM_TIMEZONE' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.ENUM_CONVERTER_ALLOW_STRING_PASSTROUGH' found, using default value 'false'.
No context init parameter 'jakarta.faces.CLIENT_WINDOW_MODE' found, using default value 'none'.
No context init parameter 'jakarta.faces.NUMBER_OF_CLIENT_WINDOWS' found, using default value '10'.
No context init parameter 'jakarta.faces.validator.DISABLE_DEFAULT_BEAN_VALIDATOR' found, using default value 'true'.
No context init parameter 'jakarta.faces.validator.ENABLE_VALIDATE_WHOLE_BEAN' found, using default value 'false'.
No context init parameter 'jakarta.faces.CONFIG_FILES' found.
No context init parameter 'jakarta.faces.LIFECYCLE_ID' found.
No context init parameter 'jakarta.faces.DISABLE_FACESSERVLET_TO_XHTML' found.
No context init parameter 'org.apache.myfaces.USE_LAMBDA_METAFACTORY' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.USE_ENCRYPTION' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.SECRET' found.
No context init parameter 'org.apache.myfaces.ALGORITHM' found, using default value 'AES'.
No context init parameter 'org.apache.myfaces.SECRET.CACHE' found.
No context init parameter 'org.apache.myfaces.ALGORITHM.IV' found.
No context init parameter 'org.apache.myfaces.ALGORITHM.PARAMETERS' found, using default value 'ECB/PKCS5Padding'.
No context init parameter 'org.apache.myfaces.SERIAL_FACTORY' found.
No context init parameter 'org.apache.myfaces.COMPRESS_STATE_IN_CLIENT' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.MAC_ALGORITHM' found, using default value 'HmacSHA256'.
No context init parameter 'org.apache.myfaces.MAC_SECRET' found.
No context init parameter 'org.apache.myfaces.MAC_SECRET.CACHE' found.
No context init parameter 'org.apache.myfaces.CONFIG_REFRESH_PERIOD' found, using default value '2'.
No context init parameter 'org.apache.myfaces.RENDER_VIEWSTATE_ID' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.STRICT_XHTML_LINKS' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.RENDER_CLEAR_JAVASCRIPT_FOR_BUTTON' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.REFRESH_TRANSIENT_BUILD_ON_PSS' found, using default value 'auto'.
No context init parameter 'org.apache.myfaces.REFRESH_TRANSIENT_BUILD_ON_PSS_PRESERVE_STATE' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.VALIDATE_XML' found.
No context init parameter 'org.apache.myfaces.WRAP_SCRIPT_CONTENT_WITH_XML_COMMENT_TAG' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.DEBUG_PHASE_LISTENER' found.
No context init parameter 'org.apache.myfaces.STRICT_JSF_2_CC_EL_RESOLVER' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.DEFAULT_RESPONSE_WRITER_CONTENT_TYPE_MODE' found, using default value 'text/html'.
No context init parameter 'org.apache.myfaces.VIEW_UNIQUE_IDS_CACHE_ENABLED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.COMPONENT_UNIQUE_IDS_CACHE_SIZE' found, using default value '100'.
No context init parameter 'org.apache.myfaces.STRICT_JSF_2_VIEW_NOT_FOUND' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.EARLY_FLUSH_ENABLED' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.STRICT_JSF_2_FACELETS_COMPATIBILITY' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.RENDER_FORM_VIEW_STATE_AT_BEGIN' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.FLASH_SCOPE_DISABLED' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.NUMBER_OF_VIEWS_IN_SESSION' found, using default value '20'.
No context init parameter 'org.apache.myfaces.NUMBER_OF_SEQUENTIAL_VIEWS_IN_SESSION' found, using default value '4'.
No context init parameter 'org.apache.myfaces.NUMBER_OF_FLASH_TOKENS_IN_SESSION' found.
No context init parameter 'org.apache.myfaces.SUPPORT_EL_3_IMPORT_HANDLER' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.STRICT_JSF_2_ORIGIN_HEADER_APP_PATH' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.STRICT_JSF_2_ALLOW_SLASH_LIBRARY_NAME' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.RESOURCE_BUFFER_SIZE' found, using default value '2048'.
No context init parameter 'org.apache.myfaces.VALIDATE' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.RESOURCE_HANDLER_CACHE_SIZE' found, using default value '500'.
No context init parameter 'org.apache.myfaces.RESOURCE_HANDLER_CACHE_ENABLED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.annotation.SCAN_PACKAGES' found.
No context init parameter 'jakarta.faces.WEBSOCKET_ENDPOINT_PORT' found.
No context init parameter 'org.apache.myfaces.WEBSOCKET_MAX_IDLE_TIMEOUT' found, using default value '300000'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_WEBSOCKET_SESSION_TOKEN' found, using default value 'secureRandom'.
No context init parameter 'org.apache.myfaces.CLIENT_VIEW_STATE_TIMEOUT' found, using default value '0'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_VIEW_STATE_SESSION_TOKEN' found, using default value 'secureRandom'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_VIEW_STATE_SESSION_TOKEN_LENGTH' found, using default value '8'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_VIEW_STATE_SESSION_TOKEN_SECURE_RANDOM_CLASS' found.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_VIEW_STATE_SESSION_TOKEN_SECURE_RANDOM_PROVIDER' found.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_VIEW_STATE_SESSION_TOKEN_SECURE_RANDOM_ALGORITHM' found, using default value 'SHA1PRNG'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_CSRF_SESSION_TOKEN' found, using default value 'secureRandom'.
No context init parameter 'org.apache.myfaces.COMPRESS_STATE_IN_SESSION' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.USE_FLASH_SCOPE_PURGE_VIEWS_IN_SESSION' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.AUTOCOMPLETE_OFF_VIEW_STATE' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.RESOURCE_MAX_TIME_EXPIRES' found, using default value '604800000'.
No context init parameter 'org.apache.myfaces.LAZY_LOAD_CONFIG_OBJECTS' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.EL_RESOLVER_COMPARATOR' found.
No context init parameter 'org.apache.myfaces.EL_RESOLVER_PREDICATE' found.
No context init parameter 'org.apache.myfaces.VIEWID_CACHE_SIZE' found, using default value '500'.
No context init parameter 'org.apache.myfaces.VIEWID_EXISTS_CACHE_ENABLED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.VIEWID_PROTECTED_CACHE_ENABLED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.VIEWID_DERIVE_CACHE_ENABLED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.validator.BEAN_BEFORE_JSF_VALIDATION' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.FACES_INIT_PLUGINS' found.
No context init parameter 'org.apache.myfaces.INITIALIZE_SKIP_JAR_FACES_CONFIG_SCAN' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.INITIALIZE_ALWAYS_STANDALONE' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.EXPRESSION_FACTORY' found.
No context init parameter 'org.apache.myfaces.CHECK_ID_PRODUCTION_MODE' found, using default value 'auto'.
No context init parameter 'org.apache.myfaces.MARK_INITIAL_STATE_WHEN_APPLY_BUILD_VIEW' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.CACHE_EL_EXPRESSIONS' found, using default value 'noCache'.
No context init parameter 'org.apache.myfaces.WRAP_TAG_EXCEPTIONS_AS_CONTEXT_AWARE' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.RESOURCE_CACHE_LAST_MODIFIED' found, using default value 'true'.
No context init parameter 'org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS' found, using default value 'dev-only'.
No context init parameter 'org.apache.myfaces.WEBSOCKET_MAX_CONNECTIONS' found.
No context init parameter 'org.apache.myfaces.RENDER_CLIENTBEHAVIOR_SCRIPTS_AS_STRING' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.ALWAYS_FORCE_SESSION_CREATION' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.RESOURCE_BUNDLE_CONTROL' found.
No context init parameter 'org.apache.myfaces.EL_RESOLVER_TRACING' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.ERROR_TEMPLATE_RESOURCE' found, using default value 'META-INF/rsc/myfaces-dev-error.xml'.
No context init parameter 'org.apache.myfaces.DEBUG_TEMPLATE_RESOURCE' found, using default value 'META-INF/rsc/myfaces-dev-debug.xml'.
No context init parameter 'org.apache.myfaces.ERROR_HANDLING' found, using default value 'false, on Development Project stage: true'.
No context init parameter 'org.apache.myfaces.TEMPORAL_RESOURCEHANDLER_CACHE_ENABLED' found, using default value 'false'.
No context init parameter 'org.apache.myfaces.SERVICE_PROVIDER_FINDER' found.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_CSRF_SESSION_TOKEN_LENGTH' found, using default value '16'.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_CSRF_SESSION_TOKEN_SECURE_RANDOM_CLASS' found.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_CSRF_SESSION_TOKEN_SECURE_RANDOM_PROVIDER' found.
No context init parameter 'org.apache.myfaces.RANDOM_KEY_IN_CSRF_SESSION_TOKEN_SECURE_RANDOM_ALGORITM' found, using default value 'SHA1PRNG'.
No context init parameter 'org.apache.myfaces.VIEW_POOL_MAX_POOL_SIZE' found, using default value '5'.
No context init parameter 'org.apache.myfaces.VIEW_POOL_MAX_DYNAMIC_PARTIAL_LIMIT' found, using default value '2'.
No context init parameter 'org.apache.myfaces.VIEW_POOL_ENTRY_MODE' found, using default value 'soft'.
No context init parameter 'org.apache.myfaces.VIEW_POOL_DEFERRED_NAVIGATION' found, using default value 'false'.


********************************************************************
*** WARNING: Apache MyFaces Core is running in DEVELOPMENT mode. ***
***                                            ^^^^^^^^^^^       ***
*** Do NOT deploy to your live server(s) without changing this.  ***
*** See Application#getProjectStage() for more information.      ***
********************************************************************


MyFaces Core has started, it took [660] ms.
quarkus-myfaces-showcase 4.1.0-RC2-SNAPSHOT on JVM (powered by Quarkus 3.2.9.Final) started in 4.304s. Listening on: http://localhost:8081
Profile test activated.
Installed features: [cdi, myfaces, servlet, smallrye-context-propagation, vertx, websockets, websockets-client]
MyFaces Core Servlet 6.0 support enabled
Chain of EL resolvers: [org.apache.myfaces.el.resolver.implicitobject.ImplicitObjectResolver@2b2f2bf1, org.apache.myfaces.core.extensions.quarkus.runtime.spi.QuarkusCdiELResolver@131960ee, org.apache.myfaces.el.resolver.CompositeComponentELResolver@509c84da, org.apache.myfaces.el.resolver.EmptyStringToNullELResolver@1c11d8b5, org.apache.myfaces.el.resolver.FlashELResolver@4eb31865, org.apache.myfaces.el.resolver.ResourceResolver@16751f4d, jakarta.el.ResourceBundleELResolver@22fbe30d, org.apache.myfaces.el.resolver.ResourceBundleResolver@303d5397, org.apache.myfaces.el.resolver.ImportConstantsELResolver@669b05c5, org.apache.el.stream.StreamELResolverImpl@582af12c, jakarta.el.StaticFieldELResolver@25b492af, jakarta.el.MapELResolver@7f4fdc65, jakarta.el.ListELResolver@41444b64, jakarta.el.ArrayELResolver@4ee861f1, jakarta.el.BeanELResolver@4f48b369]
No state saving method defined, assuming default server state saving
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 6.882 s - in org.apache.myfaces.core.extensions.quarkus.showcase.QuarkusMyFacesShowcaseTest
quarkus-myfaces-showcase stopped in 0.064s
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1
```

**Comment by melloware** [comment]
let me try your branch now.

**Comment by melloware** [comment]
OK your branch is also all passing for me locally?

**Comment by volosied** [comment]
Might just be something with my system then. Thanks for checking!

**Pull request merged**
