### PR TITLE
MYFACES-4545: 4.0 BeanValidator warning on in Development mode

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by melloware** [comment]
@bohmber it looks like the IT tests just started failing with this error..

" IntegrationTest.test » Runtime Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(Capabilities): org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 109"

**Comment by bohmber** [comment]
@melloware looks like with new Chrome version there is a problem with the IT test

**Comment by bohmber** [comment]
chromedriver version 109.0.5414.25 contains two files now.  

`chromedriver             
 LICENSE.chromedriver`

that is the reason why the IT test are failing on my local

**Comment by werpu** [comment]
Guys have a look at the chrome manager library https://github.com/bonigarcia/webdrivermanager
this takes care of choosing and loading the proper chrome driver!

**Pull request merged**
