### PR TITLE
MYFACES-4282 skip clearing view map during view metadata creation

### PR DESCRIPTION
**Pull request by wtlucy**
For https://issues.apache.org/jira/browse/MYFACES-4282

### CODE REVIEW

**Comment by tandraschko** [comment]
@wtlucy would you like to add 2 unittests for both cases?

So we could release the next version in May - the last release was in Januar.

**Comment by wtlucy** [comment]
@tandraschko sure, I'll plan to add some tests for this next week.

**Comment by wtlucy** [comment]
@tandraschko I've added some really basic tests here.  Any comments?

**Comment by tandraschko** [comment]
+1
thanks
please apply it :)

**Comment by tandraschko** [comment]
@wtlucy thanks! please don't forget 3.x

**Comment by wtlucy** [comment]
@tandraschko done :) - https://github.com/apache/myfaces/pull/50

**Pull request merged**
