### PR TITLE
MYFACES-4692: provide default implementations for getActionExpression and setActionExpression

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4692

Code looks right, but I'm getting a build error: 

`
[ERROR] Failed to execute goal org.apache.myfaces.buildtools:myfaces-builder-plugin:1.0.11:build-metadata (default) on project myfaces-api: Execution default of goal org.apache.myfaces.buildtools:myfaces-builder-plugin:1.0.11:build-metadata failed: syntax error @[48,1] in file: myfaces/api/src/main/java/jakarta/faces/component/ActionSource.java -> [Help 1]
`

### CODE REVIEW

**Comment by tandraschko** [comment]
i dont think the myfaces-builder-plugin know what a default method is

**Comment by volosied** [comment]
The -e flag gives the following exception:```
Caused by: com.thoughtworks.qdox.parser.ParseException: syntax error @[48,1] in file:/Users/volosied/opensource/myfaces/api/src/main/java/jakarta/faces/component/ActionSource.java
    at com.thoughtworks.qdox.parser.impl.Parser.yyerror (Parser.java:1018)
    at com.thoughtworks.qdox.parser.impl.Parser.yyparse (Parser.java:1324)
    at com.thoughtworks.qdox.parser.impl.Parser.parse (Parser.java:999)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource (JavaDocBuilder.java:353)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource (JavaDocBuilder.java:381)
    at com.thoughtworks.qdox.JavaDocBuilder.addSource (JavaDocBuilder.java:377)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.qdox.QdoxModelBuilder$1.processSource (QdoxModelBuilder.java:91)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils$2.visitFile (IOUtils.java:494)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk (DirectoryScanner.java:43)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk (DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk (DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk (DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk (DirectoryScanner.java:34)
    at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan (DirectoryScanner.java:52)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils.addSourceTree (IOUtils.java:488)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils.addSourceTree (IOUtils.java:475)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils.getInnerSourceClasses (IOUtils.java:456)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils.getSourceClasses (IOUtils.java:417)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.IOUtils.visitSources (IOUtils.java:403)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.qdox.QdoxModelBuilder.buildModel (QdoxModelBuilder.java:87)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.BuildMetaDataMojo.buildModel (BuildMetaDataMojo.java:649)
    at org.apache.myfaces.buildtools.maven2.plugin.builder.BuildMetaDataMojo.execute (BuildMetaDataMojo.java:464)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
```

**Comment by volosied** [comment]
@tandraschko  I think you're right.

**Comment by volosied** [comment]
Once the plugin 1.0.12 is released, I'll mark this ready for review.

**Comment by volosied** [comment]
New build: 
```
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/myfaces/buildtools/myfaces-builder-plugin/1.0.12/myfaces-builder-plugin-1.0.12.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/myfaces/buildtools/myfaces-builder-plugin/1.0.12/myfaces-builder-plugin-1.0.12.pom (7.7 kB at 27 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/myfaces/buildtools/myfaces-builder-plugin/1.0.12/myfaces-builder-plugin-1.0.12.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/myfaces/buildtools/myfaces-builder-plugin/1.0.12/myfaces-builder-plugin-1.0.12.jar (390 kB at 1.2 MB/s)
```

```
[INFO] Reactor Summary for Apache MyFaces Core 4.1 4.1.0-RC4-SNAPSHOT:
[INFO] 
[INFO] Apache MyFaces Core 4.1 - Parent ................... SUCCESS [  1.197 s]
[INFO] Apache MyFaces Core 4.1 - API ...................... SUCCESS [ 31.038 s]
[INFO] Apache MyFaces Core 4.1 - Test ..................... SUCCESS [  1.056 s]
[INFO] Apache MyFaces Core 4.1 - Impl ..................... SUCCESS [ 27.051 s]
[INFO] Apache MyFaces Core 4.1 - OSGi Bundle .............. SUCCESS [  1.846 s]
[INFO] Apache MyFaces Core 4.1 - Extensions ............... SUCCESS [  0.149 s]
[INFO] Apache MyFaces Core 4.1 - Extensions - Quarkus ..... SUCCESS [  0.171 s]
[INFO] Apache MyFaces Core 4.1 - Extensions - Quarkus - Runtime SUCCESS [  5.094 s]
[INFO] Apache MyFaces Core 4.1 - Extensions - Quarkus - Deployment SUCCESS [  1.954 s]
[INFO] Apache MyFaces Core 4.1 - Extensions - Quarkus - Showcase SUCCESS [  8.179 s]
[INFO] Apache MyFaces Core 4.1 ............................ SUCCESS [  0.427 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2024-11-22T18:23:20-05:00
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
