### PR TITLE
MYFACES-4571: 4.0 substitute tag url in native mode

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
looks ok for me, for now

**Comment by melloware** [comment]
Doing more testing today...

**Comment by tandraschko** [comment]
Same here, it would great if you disable import reorder in the IDR

**Comment by melloware** [comment]
It is disabled in MYFaces it just these imports were all over with `io.quarkus` mixed with`org. apache` so I manually sorted these just so they were group together?

**Pull request merged**
