### PR TITLE
4.0: Quarkus remove PrimeFaces

### PR DESCRIPTION
**Pull request by melloware**
Moving to PrimeFaces Quarkus Extension

### CODE REVIEW

**Comment by tandraschko** [comment]
@melloware your PR also crashed the build, please fix it

**Comment by melloware** [comment]
I looked it looks like its integration test failures not related to my change?

**Comment by melloware** [comment]
Its more Arquillian Drone errors...

```
IntegrationTest.test » Runtime Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(ChromeOptions): org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 108
```

**Comment by melloware** [comment]
@bohmber it looks like this saying "This version of ChromeDriver only supports Chrome version 108" which just started.

**Pull request merged**
