### PR TITLE
MYFACES-4544: Do not set disabled inputs as submitted values

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4544

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
+1

**Comment by volosied** [comment]
We could problem clean this up a bit by creating a method and thus reducing some of the similar code. This could be followed up on at a later time. 

Merging.

**Comment by volosied** [comment]
@tandraschko @melloware  The build for the checks in this PR looks to have run fine, but I got a notification about another build(?) here: https://github.com/apache/myfaces/actions/runs/3894271347/jobs/6648712819
 
 It failed due to: 
```
  Error:  Errors: 
Error:    IntegrationTest.test » DroneTimeout Drone creation request timed out after 60 seconds. Make sure that browser or remote server in case of remotely executed driver is running and communication with Drone haven't failed.
Error:    IntegrationTest.testPlainHtml » DroneTimeout Drone creation request timed out after 60 seconds. Make sure that browser or remote server in case of remotely executed driver is running and communication with Drone haven't failed.

 Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default) on project faceletToXhtmlMapping:
```

Any concerns here?

**Comment by melloware** [comment]
Hmmm definitely looks like the Integration tests got stuck or something?

**Pull request merged**
