### PR TITLE
https://issues.apache.org/jira/browse/MYFACES-4685:

### PR DESCRIPTION
**Pull request by werpu**
Fix for non webkit browsers in the quirks code

### CODE REVIEW

**Comment by melloware** [comment]
Does this need to go in branches above 2.3?

**Comment by werpu** [comment]
No next is not affected, the new codebase as well not

**Comment by werpu** [comment]
@volosied please give the new code a shot whether it fixes your testcase for you, then I can offer merge requests for 2.x and 3.x except next where it is not needed!

**Comment by volosied** [comment]
Fix looks good in my testing! :) 

I'll get another TCK build started for 2.3.11 again after I start on the  4.1.0-RC3

**Comment by melloware** [comment]
awesome!

**Comment by werpu** [comment]
Ok I will merge it in then so that you can proceed with the TCK

**Pull request merged**
