### PR TITLE
Apply updated  MYFACES-4606 fix

### PR DESCRIPTION
**Pull request by volosied**

### CODE REVIEW

**Comment by werpu** [comment]
Hi I want to run this changes through my tests, will be able to do that in the evening!

**Comment by werpu** [comment]
Looks like the cherry picked backport I did from the 3.0 codebase into 2.3-next!
I will run the code nevertheles through my integration tests just to make sure!

**Comment by volosied** [comment]
Please do to be sure it's all good. I back ported this fix into our project's JSF implementations via overlays and all tests passed.

**Comment by werpu** [comment]
Tests pass on 3.0 2.3 so we can merge this one in as well! (same code)

**Pull request merged**
