### PR TITLE
MYFACES-4675: 4.0 ResetValues visit tree

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko this is your ported fix from 5.0 but I don't see you doing anything with `PartialViewContextImpl.java` ???

That still just has this:

```java
    // same like UIViewRoot#ResetValuesCallback
    private static class ResetValuesCallback implements VisitCallback
    {
        public VisitResult visit(VisitContext context, UIComponent target)
        {
            if (target instanceof EditableValueHolder)
            {
                ((EditableValueHolder)target).resetValue();
            }
            return VisitResult.ACCEPT;
        }
    }
```

### CODE REVIEW

**Comment by tandraschko** [comment]
oh
so why the tests are working?

**Comment by melloware** [comment]
Good question?   so does `f:resetValues` different than `p:commandButton resetValues="true"` i know out p:commandButton goes through PartialViewContext?

**Comment by tandraschko** [comment]
ah
PartialViewContextImpl uses UIViewRoot, so it should be ok

**Comment by melloware** [comment]
good for me 😄

**Pull request merged**
