### PR TITLE
MYFACES-4581: Felix 5.1.8

### PR DESCRIPTION
**Pull request by melloware**
Fixes ConcurrentModificationException trying to build locally.

### CODE REVIEW

**Comment by melloware** [comment]
@volosied I didn't understand https://issues.apache.org/jira/browse/FELIX-6566 which is still open can you see if version 5.1.8 still has the issue you refer to?  I cannot build 4.0 locally without this plugin upgrade

**Comment by volosied** [comment]
Building with 5.18 produces the following impl manifest: 

```
Import-Package: jakarta.annotation;version="[2.1.0,3.0.0)",
javax.crypto
javax.crypto.spec
jakarta.ejb;version="[4.0.0,5.0.0)";resolution:=optional
jakarta.el
javax.naming
jakarta.persistence;version="[3.1.0,4.0.0)";resolution:=optional
jakarta.servlet
jakarta.servlet.http
jakarta.servlet.annotation;resolution:=optional
javax.xml.parsers
```

But we specify version here: 
https://github.com/apache/myfaces/blob/main/impl/pom.xml#L632-L646


Looks like it still occurs. Let me look at this again.

**Comment by melloware** [comment]
OK thanks for looking at this.

**Comment by volosied** [comment]
Even updating to the jakarta spec jars doesn't seem to fix the jakarta.el import: 

https://github.com/volosied/myfaces/pull/new/jakarta-dep-update

**Comment by volosied** [comment]
I'll try to reach out to some more people.

**Comment by melloware** [comment]
We use Felix 5.1.8 in PrimeFaces too and I don't think we have had issues so this is strange.

**Comment by tandraschko** [comment]
any news @volosied?

**Comment by tandraschko** [comment]
i need to merge this for now as all CI are failing.

**Pull request merged**
