### PR TITLE
MYFACES-4606: Fix the missing issuing element

### PR DESCRIPTION
**Pull request by werpu**
Also adds the naming container fixes for 3.0 to the 2.3x branch! (MYFACES-4533)

### CODE REVIEW

**Comment by volosied** [comment]
Could you also apply this to 2.2.x? We still have some supported users, and it would be great to have it in 2.2. Thank you.

**Comment by werpu** [comment]
I will check 2.2 tomorrow, it is already midnight here!

**Comment by volosied** [comment]
Sorry, I only meant 4606 to 2.2 ( didn't see the updates in the JIRA).

**Comment by werpu** [comment]
Perfect, will fix it later today, already have it fixed, but I need to find time to run my usual tests!

**Pull request merged**
