### PR TITLE
Quarkus native mode support

### PR DESCRIPTION
**Pull request by rmpestano**
* Enable native mode
* Adds tests on showcase module (jvm and native)

We still miss an automatic way to [register JSF managed beans](https://github.com/rmpestano/myfaces/blob/2fe17af334422284aa9362307535ecf91b2a447e/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java#L622) for reflection

### CODE REVIEW

**Comment by tandraschko** [comment]
Thanks Rafael,
I will merge it.

However i will remove the showcase from the normal build from now, to not "influence" the normal MF builds

**Comment by rmpestano** [comment]
Yes sure, thank you for the guidance on this PR!

Also for the showcase, maybe we can put it on the PrimeFaces extension module (not sure you want to have one on this repo) and maybe create a simpler showcase for pure MyFaces. This way we could cleanup this extension (mainly the required deps for PrimeFaces on runtime module, primefaces [application marker](https://github.com/apache/myfaces/blob/cdf4ea41cc3dc8f4e26c0e35ab6b420a37a972d5/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java#L404) and [resource bundle entries](https://github.com/apache/myfaces/blob/cdf4ea41cc3dc8f4e26c0e35ab6b420a37a972d5/extensions/quarkus/deployment/src/main/java/org/apache/myfaces/core/extensions/quarkus/deployment/MyFacesProcessor.java#L567-L568)), I can help in case you need, just let me know

**Comment by tandraschko** [comment]
@rmpestano  sure :)

I already splitted up the methods for now. Will commit it soon.
Also i will try to scan @Named beans and loop public getter and register them.

Some questions:

1) QuarkusExceptionHandlerFactory.class.getName(); you added this but we already collect all "ExceptionHandlerFactory" classes and impls; do we really need this?

2)
import com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl;
import com.sun.org.apache.xpath.internal.functions.FuncLocalPart;
import com.sun.org.apache.xpath.internal.functions.FuncNot;

do we really need this reflection support?

**Comment by rmpestano** [comment]
For 1, if we remove it we get:
```
java.lang.ClassNotFoundException: org.apache.myfaces.core.extensions.quarkus.runtime.exception.QuarkusExceptionHandlerFactory
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1224)
        at org.apache.myfaces.util.lang.ClassUtils.classForName(ClassUtils.java:155)

```
For some reason it not gets collected in `collectClassAndSubclasses`, I think it's because it is defined on the extension itself....

For 2, i get:

```
Could not load or parse web-fragment.xml
Could not load or parse web-fragment.xml
```

eventhough the application works without issues. I only get that message on the console and nothing more, for some reason on MacOS the native image is not generating the debug.log file, I need to test on Ubuntu to see if I get a stacktrace. This is what I got:

Screenshot 2020-03-02 at 11 37 13

**Comment by rmpestano** [comment]
By the way, I'm using this command to run the test against a generated native image:
`mvn failsafe:integration-test -Pnative -Dquarkus.test.native-image-profile=dev -Dnative.image.path=target/quarkus-myfaces-showcase-1.0-SNAPSHOT-runner -Dquarkus.log.file.path=target/debug.log` note that failsafe is overriding the quarkus.log.file.path parameter (we also have it on application.properties)

**Comment by tandraschko** [comment]
@rmpestano 
i refactored the whole thing
moved PF to own methods 
and loop all @Named beans + public fields / getters

can you give it a try?

**Comment by rmpestano** [comment]
It is working great @tandraschko, awesome work!
Also the native image size still the same, around 108 MB

**Comment by tandraschko** [comment]
great!

Can we also remove RestoreViewSupport from reflection support?

**Comment by tandraschko** [comment]
i also added DocumentBuilderFactory as class/subclass instead of using the Impl name directly

**Comment by rmpestano** [comment]
> Can we also remove RestoreViewSupport from reflection support?

Yes, we can 👍

**Comment by rmpestano** [comment]
If someone is watching this thread and uses a MacOS (probably also linuxes distros), can you try to run following native binary and access localhost:8080/index.xhtml? 

https://drive.google.com/open?id=1m7pNtWu3Gz7YVXkcJH-fqMYVP45GennE

**Comment by tandraschko** [comment]
great, removed it!

I will try to setup the PF quarkus soon

**Comment by wtlucy** [comment]
@rmpestano at a glance, the binary runs fine on my MacOS Mojave system

**Comment by rmpestano** [comment]
Thank you for looking at it @wtlucy!

**Comment by rmpestano** [comment]
Following is the linux_x86 native image, if someone wants to try:
 https://drive.google.com/open?id=1hf_Vyflz732_RFzX9S7C3wYlDWJaCWFP

I've tested on Ubuntu 18.04.4

**Pull request merged**
