### PR TITLE
Integration Tests

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko this is my branch and its getting an error with a mismatch of Tomcat not having some Cookie attribute because I think it thinks its Servlet 6.0 mode

### CODE REVIEW

**Comment by tandraschko** [comment]
did you also check the mvn dependency:tree?

**Comment by melloware** [comment]
@tandraschko here is the error I am getting locally. I had to update some JARS just to get this far in Inegration tests but it seems like some kind of Tomcat servlet mismatch.

```
org.apache.catalina.core.ApplicationSessionCookieConfig 
does not define or inherit an implementation of the resolved method 
abstract java.lang.String getAttribute(java.lang.String)' of interface jakarta.servlet.SessionCookieConfig.
```

Full stack:
```
SEVERE: Servlet.service() for servlet [FacesServlet] in context with path [/faceletToXhtmlMapping-4.0.0-SNAPSHOT] threw exception [Receiver class org.apache.catalina.core.ApplicationSessionCookieConfig does not define or inherit an implementation of the resolved method 'abstract java.lang.String getAttribute(java.lang.String)' of interface jakarta.servlet.SessionCookieConfig.] with root cause
java.lang.AbstractMethodError: Receiver class org.apache.catalina.core.ApplicationSessionCookieConfig does not define or inherit an implementation of the resolved method 'abstract java.lang.String getAttribute(java.lang.String)' of interface jakarta.servlet.SessionCookieConfig.
        at org.apache.myfaces.context.flash.FlashImpl._createFlashCookie(FlashImpl.java:1194)
        at org.apache.myfaces.context.flash.FlashImpl._saveRenderFlashMapTokenForNextRequest(FlashImpl.java:774)
        at org.apache.myfaces.context.flash.FlashImpl._manageFlashMapTokens(FlashImpl.java:889)
        at org.apache.myfaces.context.flash.FlashImpl.doPrePhaseActions(FlashImpl.java:197)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:155)
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:125)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:223)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:224)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:159)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```

**Comment by melloware** [comment]
OK going back to 10.0 broke the main build.  Going to 10.1.4 everywhere fixed my local and now everything is running properly but still failing on the server.  I had to bump TomCat Jasper EL from 9.0 to 10.1.4 because it was brining in an old servlet.jar.

But now its still failing on GitHub but there is really NO info in the logs.

**Comment by tandraschko** [comment]
maybe there are some configs like surefire plugin to not cut the stacktrace?

**Comment by tandraschko** [comment]
surefire has trimStackTrace flag

**Comment by melloware** [comment]
Got the stack trace!  Looks like its some sort of file mismatch?  Maybe OS related Linux vs Windows?

```
Caused by: java.lang.IllegalArgumentException: File for import does not exist: /home/runner/work/myfaces/myfaces/integration-tests/faceletToXhtmlMapping/target/faceletToXhtmlMapping-4.0.0-SNAPSHOT.war
	at org.jboss.shrinkwrap.api.ArchiveFactory.createFromZipFile(ArchiveFactory.java:179)
```

```
Error:  org.apache.myfaces.core.integrationtests.IntegrationTest  Time elapsed: 9.406 s  <<< ERROR!
java.lang.RuntimeException: Could not invoke deployment method: public static org.jboss.shrinkwrap.api.spec.WebArchive org.apache.myfaces.core.integrationtests.IntegrationTest.createDeployment()
	at org.jboss.arquillian.container.test.impl.client.deployment.AnnotationDeploymentScenarioGenerator.invoke(AnnotationDeploymentScenarioGenerator.java:128)
	at org.jboss.arquillian.container.test.impl.client.deployment.AnnotationDeploymentScenarioGenerator.generateDeploymentContent(AnnotationDeploymentScenarioGenerator.java:91)
	at org.jboss.arquillian.container.test.impl.client.deployment.AnnotationDeploymentScenarioGenerator.generateDeploymentContent(AnnotationDeploymentScenarioGenerator.java:50)
Dec 19, 2022 2:37:11 PM org.apache.coyote.AbstractProtocol pause
	at org.jboss.arquillian.container.test.impl.client.deployment.AbstractDeploymentScenarioGenerator.generate(AbstractDeploymentScenarioGenerator.java:30)
INFO: Pausing ProtocolHandler ["http-nio-8888"]
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:81)
Dec 19, 2022 2:37:11 PM org.apache.catalina.core.StandardService stopInternal
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO: Stopping service [arquillian-tomcat-embedded-8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Dec 19, 2022 2:37:11 PM org.apache.coyote.AbstractProtocol stop
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO: Stopping ProtocolHandler ["http-nio-8888"]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Dec 19, 2022 2:37:11 PM org.apache.coyote.AbstractProtocol destroy
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
INFO: Destroying ProtocolHandler ["http-nio-8888"]
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:89)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:163)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.arquillian.container.test.impl.client.deployment.AnnotationDeploymentScenarioGenerator.invoke(AnnotationDeploymentScenarioGenerator.java:126)
	... 54 more
Caused by: java.lang.IllegalArgumentException: File for import does not exist: /home/runner/work/myfaces/myfaces/integration-tests/faceletToXhtmlMapping/target/faceletToXhtmlMapping-4.0.0-SNAPSHOT.war
	at org.jboss.shrinkwrap.api.ArchiveFactory.createFromZipFile(ArchiveFactory.java:179)
	at org.jboss.shrinkwrap.api.ShrinkWrap.createFromZipFile(ShrinkWrap.java:185)
	at org.jboss.shrinkwrap.resolver.impl.maven.embedded.BuiltProjectImpl.getDefaultBuiltArchive(BuiltProjectImpl.java:80)
	at org.apache.myfaces.core.integrationtests.IntegrationTest.createDeployment(IntegrationTest.java:50)
	... 59 more
```

**Comment by bohmber** [comment]
If I enable integration-test without any other modification it runs successful

```
[INFO] Apache MyFaces Core 4.0 - Parent ................... SUCCESS [  1.997 s]
[INFO] Apache MyFaces Core 4.0 - API ...................... SUCCESS [  9.680 s]
[INFO] Apache MyFaces Core 4.0 - Test ..................... SUCCESS [  2.466 s]
[INFO] Apache MyFaces Core 4.0 - Impl ..................... SUCCESS [02:23 min]
[INFO] Apache MyFaces Core 4.0 - OSGi Bundle .............. SUCCESS [  6.048 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests ........ SUCCESS [  0.086 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - faceletToXhtmlMapping SUCCESS [ 18.188 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - faceletToXhtmlMappingDisabled SUCCESS [ 17.223 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - exactMapping SUCCESS [ 20.377 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - autoLookupExpressionFactoryWithoutJSP SUCCESS [ 15.087 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - protectedViews SUCCESS [ 13.194 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - ajax . SUCCESS [ 16.800 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - automaticExtensionlessMapping SUCCESS [ 12.246 s]
[INFO] Apache MyFaces Core 4.0 ............................ SUCCESS [  0.181 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by melloware** [comment]
@bohmber it does for me and Thomas too locally but its failing on GitHub Actions with the above error.

**Comment by bohmber** [comment]
@melloware which maven version is used on the github runner?

**Comment by melloware** [comment]
I believe GitHub Actions uses Maven 3.8.5 however I see these lines in the Integration Tests which is maybe Arquillian or someting...

```
2022-12-19T14:37:03.7557804Z INFO: Initialized Spacelift from defaults, workspace: /home/runner/work/myfaces/myfaces/integration-tests/faceletToXhtmlMapping, cache: /home/runner/.spacelift/cache
2022-12-19T14:37:03.7559099Z Resolver: downloading Maven binaries from https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz to /home/runner/.arquillian/resolver/maven/apache-maven-3.3.9-bin.tar.gz
2022-12-19T14:37:08.5645173Z ................................................
2022-12-19T14:37:08.6659871Z Resolver: Successfully extracted maven binaries from /home/runner/.arquillian/resolver/maven/apache-maven-3.3.9-bin.tar.gz
```

Looks like it download and extracts 3.3.9 especially?

**Comment by bohmber** [comment]
I have the same in my logs. Can you add -V to the maven cmdline

**Comment by melloware** [comment]
Done and here is what it prints out...

```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/share/apache-maven-3.8.6
Java version: [11](https://github.com/apache/myfaces/actions/runs/3733216640/jobs/6333708669#step:5:12).0.17, vendor: Eclipse Adoptium, runtime: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.17-8/x64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-1024-azure", arch: "amd64", family: "unix"
```

**Comment by melloware** [comment]
I just ran locally with Maven 3.8.6 and Adopt OpenJDK 11.0.17 which both are the same as GitHub actions and it works fine.

**Comment by melloware** [comment]
Closing in favor of: https://github.com/apache/myfaces/pull/443

**Pull request closed without merging**
