### PR TITLE
MYFACES-4606 Follow up: do not send values for unselected radio / checkbox elements

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4606

### CODE REVIEW

**Comment by werpu** [comment]
Not needed:    if (item && item.type &&
            (item.type.toLowerCase() == "submit" ||
             item.type.toLowerCase() == "button" )) {

The original behavior is somewhat different anyway... i just changed it somehow for the new code to cover more elements (aka every element)
Hence I never have issued a pr for the old code it does not expose the problem!

Either way we theoretically could unify the behavior for all branches, the old code and new code that would be feasible, if wanted, given this is a non standard behavior we are free here to do whatever we want!

**Comment by volosied** [comment]
If I removed the code to just 
```
    appendIssuingItem: function (item, targetBuf) {
        // if triggered by a Button send it along
        if (item && item.type) {

            // do not append if unselected
            if ((item.type == "checkbox" || item.type == "radio") 
             && !item.checked) {
                return;
            }
            
            //buttons not always have a name unlike inputs
            targetBuf.append(item.id || item.name, item.value);
        }
    },
```

then I see the form sent as an array.
Screenshot 2023-10-24 at 3 53 59 PM
Looks like it's caused by the preprocessed data also containing the issuing element? 

Screenshot 2023-10-24 at 3 54 33 PM


Otherwise, with the existing checks, only true is sent: 

    
Screenshot 2023-10-24 at 3 50 50 PM

**Comment by volosied** [comment]
@werpu  What do you recommend here?

**Comment by werpu** [comment]
Yes the original code only allows submits and buttons to be appended as issuing item, I guess we have to replicate the 4.x behavior into the old code might make sense to have a unified behavior, I will prepare something the next few days!

**Comment by volosied** [comment]
@werpu  Any updates? Thank you

**Comment by volosied** [comment]
I would like to merge this if possible soon in order to get new 2.3 3.0 4.0 etc releases out.

**Comment by werpu** [comment]
Hi I will work on the issue today!
Sorry was not aware that it is so urgent.

**Comment by werpu** [comment]
I have issued a pull request for 2.3-next, will also issue one for 3.0, please see: 
https://github.com/apache/myfaces/pull/637

my integration tests pass, it is basically a backport from 4.0

**Comment by volosied** [comment]
Closing in favor of #638.

**Pull request closed without merging**
