### PR TITLE
MYFACES-4524: Generate Correct Resource Path in Non-Faces Requests

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4524

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
did you run the integration tests? we have some of them which tests servlets mappings
otherwise we have to fix them first

**Comment by volosied** [comment]
@tandraschko  What do you mean? The CI build passed, as well as my local build.

**Comment by tandraschko** [comment]
If you check our root pom, integration Tests are excluded from build currently
We need to fix then

**Comment by volosied** [comment]
All green 🚀

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache MyFaces Core 4.0 4.0.0-SNAPSHOT:
[INFO] 
[INFO] Apache MyFaces Core 4.0 - Parent ................... SUCCESS [  4.497 s]
[INFO] Apache MyFaces Core 4.0 - API ...................... SUCCESS [ 21.787 s]
[INFO] Apache MyFaces Core 4.0 - Test ..................... SUCCESS [  5.581 s]
[INFO] Apache MyFaces Core 4.0 - Impl ..................... SUCCESS [02:30 min]
[INFO] Apache MyFaces Core 4.0 - OSGi Bundle .............. SUCCESS [  3.809 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests ........ SUCCESS [  0.067 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - faceletToXhtmlMapping SUCCESS [01:09 min]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - faceletToXhtmlMappingDisabled SUCCESS [ 25.172 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - exactMapping SUCCESS [ 28.463 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - autoLookupExpressionFactoryWithoutJSP SUCCESS [ 26.317 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - protectedViews SUCCESS [ 27.080 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - ajax . SUCCESS [ 32.712 s]
[INFO] Apache MyFaces Core 4.0 - Integration Tests - automaticExtensionlessMapping SUCCESS [ 26.755 s]
[INFO] Apache MyFaces Core 4.0 ............................ SUCCESS [  0.392 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:04 min
[INFO] Finished at: 2022-12-09T20:26:42-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by tandraschko** [comment]
Can you uncomment them that its included in build again?

**Pull request merged**
