### PR TITLE
MYFACES-4293: handle BigInteger in NumberConverter

### PR DESCRIPTION
**Pull request by trettstadtnlb**
Change-Id: I1586ff486a5aa8b395606c76462e473bd6d60e4e

### CODE REVIEW

**Comment by trettstadtnlb** [comment]
https://issues.apache.org/jira/browse/MYFACES-4293

**Comment by tandraschko** [comment]
Thanks for the PR!
If you would like to see it in a specific branch, please provide a nother PR.
master branch == 3.x

**Comment by trettstadtnlb** [comment]
Ok, thanks. I created PRs for 2.1.x, 2.2.x and 2.3.x. Since we are using WebSphere we now have to hope that IBM will use one of the bugfix versions from these branches.

**Comment by trettstadtnlb** [comment]
Just double-checked which MyFaces version our WebSphere uses and it's still 2.0.17, so I also created a PR for the 2.0.x branch.

**Comment by wtlucy** [comment]
Thanks for the PR @trettstadtnlb!  If you're using WebSphere Liberty, [opening an issue against that project](https://github.com/OpenLiberty/open-liberty/issues) will expedite getting this fix pulled in.

**Pull request merged**
