### PR TITLE
MYFACES-4425: Save ui input state in repeat

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4425

Thoma's fix (in jira comment) might be better, but I opted to just to change the one return for now.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
IMO we should not make it per default
we didnt had any user since 10 years which requires this

can someone start a dicussion with mojarra team?

otherwise i would introduce a webcontext param

**Comment by volosied** [comment]
@tandraschko Following up regarding the comment above.

**Comment by volosied** [comment]
I added a new web parameter: `org.apache.myfaces.UI_REPEAT_STATE_SAVING`, but the new behavior is the default.

**Comment by pnicolucci** [comment]
@tandraschko are you ok with this enabled by default? Or are you thinking we should create a TCK Challenge for this test/behavior? I think we need to either make this the default behavior or challenge the tck.

**Comment by tandraschko** [comment]
Could anyone check that case again and talk with the Mojarra guys, if this case is really required?
As i said in my small statement in the linked issue, we have this "issue" since 10 years propably and noone ever openend a JIRA issue
maybe because the case is not that valid

Otherwise i'm ok with it

**Comment by volosied** [comment]
Challenge was accepted, so I'll close this PR.

**Pull request closed without merging**
