### PR TITLE
https://issues.apache.org/jira/browse/MYFACES-4680:

### PR DESCRIPTION
**Pull request by werpu**
Client side fix, adding the latest js code to the merge request

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
please dont forget 4.1 and 5.0

**Review by volosied — APPROVED** [review]
This fixes the TCK test :) 

thank you for the PR!

**Comment by volosied** [comment]
`myfaces.ab('j_id_c', event, 'renderAjaxOutput', '', 'ajaxOutput')`  -- maybe a future revision could look for form where the render argument (ID value) is located? 

But I think this change is good enough for this test (and no users have reported this so far).

**Comment by werpu** [comment]
That was not the problem if the TCK test, the problem was that the render ID was outside of any form, but given there is exactly one form in the page it was safe enough to use that one for the viewstate handling!
It still would fail with a two form setup, but then you could use a form passthrough parameter to reference the form you want to use (a feature Mojarra probably does not have in its js implementation, but perfectly html5 compliant)

**Comment by werpu** [comment]
I will start take care of https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4685 tomorrow, I want to wrap up the other branches with the websocket fix today!

**Pull request merged**
