### PR TITLE
Faces 5.0: MYFACES-4627: Remove unused code

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4627

### CODE REVIEW

**Comment by tandraschko** [comment]
master is 4.1 currently

**Comment by volosied** [comment]
I feel that we should skip 4.1, and start on 5.0. 

I'll have the PRs up anyway and can edit the target branch.

**Comment by tandraschko** [comment]
Thats up to the specs if we skip 4.1 or not

**Comment by tandraschko** [comment]
Conflicts now
Feel free to merge after fixing it

**Comment by volosied** [comment]
Didn't realize my main branch was used -- I'll have to re do the code..

**Pull request closed without merging**
