### PR TITLE
MYFACES-4476: New Faces.js integration tests (target 4.0.0 RC3)

### PR DESCRIPTION
**Pull request by werpu**
I have ported my set of 20 integration tests, i have used for developing the jsf.js and faces.ts scripts in an upgraded version which use the newest client side frameworks for testing.

### CODE REVIEW

**Comment by werpu** [comment]
Sorry, i disovered some issues, I am closing the pr and will reissue it again later

**Comment by werpu** [comment]
I have fixed now the codebase, all tests pass on the new files, one fails on the old codebase.
For now I have enabled the new faces.js codebase for build and will enable the standard include once the new codebase is merged. I am not going to fix the failing test on the old codebase anymore.
(it is very likely a bug still referencing the old namespace)

**Comment by melloware** [comment]
Running build

**Comment by werpu** [comment]
Integration tests are now basically ready for merge, but before the merge we have to retarget the faces.js include in the imports.xhtml file.
Atm it is pointing towards at my embedded github implementation which is the downstream for myfaces.

**Review by melloware — APPROVED** [review]

**Pull request closed without merging**
