### PR TITLE
MYFACES-4595: Quarkus Dev UI Card

### PR DESCRIPTION
**Pull request by melloware**
image

### CODE REVIEW

**Comment by pnicolucci** [comment]
@melloware looks like the JIRA you reference is off by one :) It should be MYFACES-4595, can you update it? currently, it is linking to: https://issues.apache.org/jira/browse/MYFACES-4594

**Comment by melloware** [comment]
Sorry yep let me fix

**Comment by melloware** [comment]
I fixed the title but I wonder if I have to fix the commit message for it to take effect?

**Comment by pnicolucci** [comment]
> I fixed the title but I wonder if I have to fix the commit message for it to take effect?

Not sure, but would be good to clean up the commit message any how.

**Comment by melloware** [comment]
OK commit message fixed and ticket is now linked properly

**Pull request merged**
