### PR TITLE
MYFACES-4376

### PR DESCRIPTION
**Pull request by bohmber**
Update Cryptographic algorithm in StateUtils to a stronger version

### CODE REVIEW

**Comment by tandraschko** [comment]
+1

please also add it to 2.3-next, thats the only version currently usable by Quarkus users and its the same codebase as 4.0

**Comment by bohmber** [comment]
It's based on this https://github.com/apache/myfaces/security/code-scanning

**Comment by tandraschko** [comment]
also dont forget the homepage

**Comment by bohmber** [comment]
@tandraschko 

Is 2.3-next just a improved replacement for 2.3.x? If yes then I shouldn't apply the change to AES for 2.3-next

**Comment by tandraschko** [comment]
somehow yes, in general its a completely cleaned-up 2.3, which i created as preperation for 4.0.
Currently 2.3-next equals 4.0, but with jakarta namespace and @ClientWindowScoped prototype.

**Comment by bohmber** [comment]
@volosied should I apply this to 3.0.x as well?

**Pull request merged**
