### PR TITLE
Quarkus 3 Preview

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko Quarkus 3 in beta for Jakarta EE 10.  I tried to upgrade but there are some MyFaces JSF changes that are above my level of understanding.

Here is how far I fgot...

### CODE REVIEW

**Comment by tandraschko** [comment]
@melloware fixed compile errors but still not building:

Quarkus Extension Dependency Verification Error
The deployment artifact org.apache.myfaces.core.extensions.quarkus:myfaces-quarkus-deployment::jar depends on the following Quarkus extension deployment artifacts whose corresponding runtime artifacts were not found among the dependencies of org.apache.myfaces.core.extensions.quarkus:myfaces-quarkus:jar:4.0.0-SNAPSHOT:
 org.apache.myfaces.core.extensions.quarkus:myfaces-quarkus-deployment:jar:4.0.0-SNAPSHOT
*  io.quarkus:quarkus-undertow-deployment:jar:3.0.0.Alpha2

**Comment by tandraschko** [comment]
fixed that but javac crashes, maybe you can try on your machine

**Comment by tandraschko** [comment]
ok, compiles with newer JDK version
following 2 errors left: ContextRegistrarBuildItem and BeanRegistrarBuildItem is not available anymore
quarkus API has been changed

**Comment by tandraschko** [comment]
ok, the showcase starts now but only with a hack in QuarkusFacesInitializer
@melloware can you try to ask the (or even debug a bit) why our StartupServletContextListener#contextInitialized is called 2 times? 

Also if you open index.xhtml, java.lang.NullPointerException - Bean is null will be thrown
so there is still something weird

**Comment by melloware** [comment]
Awesome!  Let me do some debugging!

**Comment by melloware** [comment]
OK here is the class the BeanManager can't find:
image

I am wondering because its "$Bridge"???

**Pull request merged**
