### PR TITLE
Myfaces-4281

### PR DESCRIPTION
**Pull request by jfmaurel**
changes in o.a.m..view.facelets.compiler.SAXCompiler (skip html namespaces unit compilation)
add org.apache.myfaces.view.facelets.compiler;SkipNamespaceUnitTest.java
add test resource testSkipNamespaceUnit.xhtml

### CODE REVIEW

**Comment by tandraschko** [comment]
Great contribution!
Could you please don't change our formattings? Otherwise it's hard to check changes and we have a own checkstyle in MyFaces.

**Comment by jfmaurel** [comment]
Sorry for that, I used my own settings in Eclipse by inadvertance.
What should I do now to correct that ?

**Comment by tandraschko** [comment]
at best disable the eclipse autoformatting and re-apply your changes.
You can then refresh your PR or create a new PR (please google about that)

**Comment by tandraschko** [comment]
Looks good now!
Very good contribution - thanks.
I will port it to 2.3.x.

**Pull request merged**
