### PR TITLE
MYFACES-4602: Fixes coming in from the github upstream.

### PR DESCRIPTION
**Pull request by werpu**
Updating also the client dependencies to the latest versions!

Code passes all needed tests, and also has been tested by Tobago!

### CODE REVIEW

**Comment by werpu** [comment]
Guys the integration test chrome driver needs an update againm this is why the integration tests fail:

Error:    IntegrationTest.testPlainHtml » Runtime Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(ChromeOptions): org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 110

**Comment by werpu** [comment]
I will merge nevertheless, the build problems have nothing to do with my code.
The built atm simply is broken! No need to hold off with my PR since the relevant tests pass on it!

**Comment by bohmber** [comment]
Please change the version directly in [.github/workflows/myfaces-ci.yml](https://github.com/apache/myfaces/tree/main/.github/workflows/myfaces-ci.yml) you can specify the chromeDriverVersion in the mvn cmd line

**Comment by werpu** [comment]
Hi, I can have a look at it in the afternoon, I am project bound until then.
Otherwise someone else can go ahead!

But thanks for the hint!


Am Fr., 21. Apr. 2023 um 08:16 Uhr schrieb Bernd Bohmann <
***@***.***>:

**Pull request merged**
