### PR TITLE
MYFACES-4680

### PR DESCRIPTION
**Pull request by volosied**
https://issues.apache.org/jira/browse/MYFACES-4680

TCK uses a viewscoped bean (not app scoped), and I'm assuming that  since app scope is null, it returns an empty collection. 

MYFACES-4680 still needs more work because a JavaScript error occurs: 

```
"makeException@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2496:16
assertFormExists@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2633:19
getForm@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2554:25
resolveForm@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:2956:27
request@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:532:60
request@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:135:39
ab@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:261:128
.renderAjaxOutput<@http://localhost:9080/test-faces23-websocket/spec1396ViewScopedWebsocket.xhtml:23:237
onmmessage@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1235:45
./typescript/faces/impl/PushImpl.ts/bindCallbacks/this.socket.onmessage@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1282:53
EventHandlerNonNull*bindCallbacks@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1282:13
open@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1181:18
open@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1151:116
open@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:221:33
init@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:1145:212
init@http://localhost:9080/test-faces23-websocket/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development:212:33
@http://localhost:9080/test-faces23-websocket/spec1396ViewScopedWebsocket.xhtml:23:12
"
```

### CODE REVIEW

**Comment by melloware** [comment]
@milansie did some work on WebSockets recently as well.

**Comment by volosied** [comment]
Please take a look @milansie.  I noticed that applicationScope was null, so it ever got to the viewScope check. Perhaps another approach should be taken, but this PR made sure the message was sent. 

As for the javascript error,  the page works fine as-is in Mojarra. However, if I move the websocket element into the form, it works fine. 

This aspect might be a potential challenge?  @werpu something could you look into (whenever you have time)

**Comment by volosied** [comment]
Although, looking at some of the javadocs, it doesn't look like f:websocket is required to be in a form.

For instance see the ajax section of JSF 2.3's Push description: https://jakarta.ee/specifications/faces/2.3/apidocs/?javax/faces/push/PushContext.html

**Comment by volosied** [comment]
@milansie  Which servers are you testing this on?

**Comment by milansie** [comment]
@volosied  usually tomcat 10.1.25

just tried to go through js exception on my environment, and it doesn't occur, because the element which should be in the form was the button (which was in the form), not f:websocket

**Comment by volosied** [comment]
The exception only occurs if you include the proposed fix in this PR. Otherwise, I don't see how you don't get the same behavior as me?   I enabled the app with CDI ( [as described here](https://balusc.omnifaces.org/2013/10/how-to-install-cdi-in-tomcat.html))  and it still failed. 

I tested tomcat, and the websocket connection opened (and confirmed via the "added" text). However, when I pressed the "push" button, the "pushed" text doesn't display.

applicationScope is null, as shown here: 

image

**Comment by volosied** [comment]
I also don't understand why appScope is null.   If something is wrong with the app, please point it out because I don't see anything obvious. 

https://github.com/jakartaee/faces/tree/4.1.0-RELEASE/tck/faces23/websocket

**Comment by volosied** [comment]
` scope="application"` sets the scope, which explains why app scope is null.   

Please review this PR.  The JavaScript can be handled separately.

**Comment by milansie** [comment]
> ` scope="application"` sets the scope, which explains why app scope is null.

hm, it's weird.. because ...  _The default scope is application. When the user attribute is specified, then the default scope is session._

https://jakarta.ee/specifications/platform/9/apidocs/jakarta/faces/component/uiwebsocket

in same way it should be implemented in impl/src/main/java/org/apache/myfaces/push/WebsocketComponentRenderer.java

**Comment by volosied** [comment]
As mentioned, if you apply this fix, the test still fails because of the JavaScript exception I posted in the description. The websocket element is outside the form, and the JavaScript code throws an exception. 

The element is generated here: https://github.com/apache/myfaces/blob/b062baf626ff40e44c74baaed41a00a5c060a9d6/impl/src/main/java/org/apache/myfaces/push/WebsocketComponentRenderer.java#L92-L109

Generated HTML: 
```
<div id="j_id_c" style="display:none"></div>
```

The form check should be ignored for this scenario -- perhaps we can add a special flag in the ID so that the form check is skipped?  Or how can the JavaScript know to ignore this element ahead of time?

**Review by melloware — APPROVED** [review]

**Comment by volosied** [comment]
@werpu  Would you be able to look at this from the JS side?  I posted the stacktrace is the description. 

The websocket code is generated  `<div id="j_id_c" style="display:none"></div>` is created outside the form, and that's the assertion error that is encountered when the behavior callback is executed. 


To reproduce: 
If you use this PR and run the app from the JIRA, you should be able to reproduce this problem. Note, you need to visit the `spec1396UserScopedWebsocket` page first and then you test out `spec1396ViewScopedWebsocket`.


My thoughts: I was thinking to add a  prefix/suffix`jsf_websoket` to the generated id code, and have the `assertFormExists` method ignore this element if that prefix/suffix is found?

**Comment by volosied** [comment]
@werpu  Just following up again if you could take a look.

**Comment by volosied** [comment]
Although,  I was looking more into the JS code and found this: 

https://github.com/apache/myfaces/blob/743585934bd8210667d0aa67dadc614ceb616f3d/api/src/client/typescript/faces/impl/AjaxImpl.ts#L270-L272

How can we add a dummy form here?

**Comment by werpu** [comment]
Hi sorry for answering late, I am extremely busy with day work today. I will look into it later this week.

**Comment by volosied** [comment]
Not a problem. Thank you!

**Comment by werpu** [comment]
Hi I have added a pull request for the needed client side fixes: https://github.com/apache/myfaces/pull/769
What I noticed is that your pr is based on an old 4x. codebase 2 fixes on the js side which are in the main repository branches are not in the pr branch, you might run a merge/rebase on it!

**Pull request merged**
